### ISSUE TITLE
Guided Installer: Create DMS Wrapper Script

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#66] opened 2020-08-19 02:24 UTC
Refer to https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-DMSWrapperScript

## Objective
To verify that the user has installed all the pre -requisite softwares as mentioned on the Doc Site 

## Acceptance Criteria:
Below message needs to be displayed on CLI before executing the validation script.
"Some basic system prerequisites are required to install the Overture DMS.  For a complete list of system requirements, please see the documentation:  overture.bio/documentation/DMS/Software-Requirements
We will check to verify that these are installed." 

Case1:  Example of successful validation
Checking all software requirements: 
>> Checking Docker engine >=19.03.12....... verified!
>> Checking Bash >= 5.0.0......... verified!

Checking all hardware requirements:

>> At least 4 threads........verified!
>> Requires at least 8GB of RAM.......verified!
>> Requires at least 20GB of disk space.....verified!

All system requirements have been met! 

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/748a9651-a371-49ff-97b6-e4cacd231182)

Case 2: Example of non successful validation
In case any one of the pre-requisites is missing, the set up should exit with message as shown below.
>> Checking Docker....... installation not found! 
System requirements have not been met.  Please verify that all pre- requisite have been installed - For an exact list please see: overture.bio/documentation/DMS/Software-Requirements. 
>> Exiting installation. 

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/6eb2d5f9-ff76-4ab7-a22d-45dadc4edff0)
- [ ] Once the user has installed all the dependencies, the process will repeat and the script will run again until we reach success message.

## Dev task

- [ ] checks the minimum HW and SW requirements before executing the dms command in a docker container
- [ ] pulls the intended dms docker image. If run for the first time, will pull the latest
- [ ] is agnostic to dms version. This script does not change, even when the dms version changes.
- [ ] is to be distributed for public download. It is the entry point to the dms software in a dockerized environment.\
- [ ] minimizes the amount of commands the user needs to run, to just 1 command.

**Comment by gokul472** [comment] 2020-09-14 19:21
@b-f-chan - this might go to Sprint 6

**Comment by b-f-chan** [comment] 2020-09-17 15:30
Closing as duplicate of https://github.com/overture-stack/dms/issues/1

**Closed as completed** 2020-09-17 15:29 UTC
Labels: duplicate, canarie, dms
