### ISSUE TITLE
Doc Site: Spike - how to structure the Doc site in Gatsby

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#72] opened 2020-08-20 20:19 UTC
## Objective
- [ ] How to structure the Doc Site?
- [ ] Will it be hard codid or dynamic? The navigation will be hard codid.
- [ ] How the parent and the child relations will be maintained? It will through the JSON file. 
- [ ] How to create central repo for all doc, so that we have one source of truth? get specific files fro specific repos, there maybe some changes needed. it is TBD for now

## Expected Outcome
- [ ] Research how Amazon did their documentation?
- [ ] Keep the docs for the respective services local to the repo

Note: This will be for the Developers, users and the Administrator

Links for reference:
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/ef4b6e4a-94e5-4113-8723-5ae1db86b76c)

**Comment by samrichca** [comment] 2020-09-09 16:37
## Doc site structure

File structure:

- /documentation
-- index.md (landing page for documentation)
-- /song
--- index.md (landing page for song)
--- installation.md

URL structure:

- /documentation
- /song
- /song/installation

## Navigation structure

### Megamenu

Megamenu nav items are hard-coded in a JS object in the megamenu React component.

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/955866bc-23ab-4f76-9ae1-fbea83c863f6)

### Between documentation pages

i.e. left sidebar, prev/next, possibly a list of pages on each section's landing page - and any other parent/child/sibling page relationships

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/79e3ff52-a79e-4fbe-90ee-ce2e11196cfb)

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/6eb9b920-959e-45f1-b364-5872e46a7b82)

This navigation will be described in a JSON manifest. We're not sorting pages alphabetically/chronologically so we need to manually create a page tree. Something like this:

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/fc697899-21bd-47db-9ffa-89fa3cc5bea4)

### Navigating within the page

The right sidebar nav will be automatically generated based on headings in the Markdown document (tableOfContents object is generated when Markdown is processed).

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/d596efdd-9b04-4832-a31d-774b09e83b96)

**Comment by rtisma** [comment] 2020-09-15 13:08
Tested repo cloning via `gatsby-source-git` module. Some work can be found at https://github.com/overture-stack/website/tree/rtisma-test
Was able to get gatsby to clone song, score and ego repos, and index their files so that its searchable via graphql. 

After discussions with Sam, every overture repo shall follow these rules:
1. All documentation is written in markdown files (.md)
2. Multiple .md files can be used. It is suggested they are put in a directory (i.e ./docs or similar directory)
3. An `index.md` will be available in each repo, as an entry point

In addition, the only piece of information that needs to be hard coded are the names of the overture repos, their github url and the relative location of their index.md files. With this, as new versions of the repos are released, all that we need to do on the gatsby side is update the gatsby-config.js file with the new release version, and the rest should be dynamic.

Regarding CI/CD, netlify will continue to be used. We can configure netlify to auto deploy the site when there is a merge to master. In order to update documentation for a specific repo, a developer needs to update the repos release number in the `gatsby-conifg.js` and then create a PR against the `master` branch. When that is reviewed and merged, only then will netlify redeploy. This allows us to control when to release new documentation.

**Comment by samrichca** [comment] 2020-09-15 15:48
Deployment:
- Use the release tag name as the branch name when configuring gatsby-source-git.
- When updating the branch/tag name, make a PR on master. Netlify will build a draft automatically for testing.

Folder structure (needs additional investigation once we have Markdown processing available):
- Does *every* folder (and subfolder, etc) need an index.md? (This is for web UX, rather than an under-the-hood entry point.)
- How are pages ordered, i.e. for navigation purposes? There must be organization in place already - the issue is making it consistent & Gatsby-friendly.
- Do we need to add YAML/front matter (title, date, etc) to MD files for Gatsby processing?
- Can we do post-processing on the MD files we import to make them fit the site's conventions?

**Comment by b-f-chan** [comment] 2020-09-18 09:58
Findings reviewed with team at Sept 17, 2020 sprint planning - Team consensus to proceed with Markdown POC (#87).  Closing.

**Closed as completed** 2020-09-18 09:59 UTC
Labels: canarie
